CREATE TABLE IF NOT EXISTS stations (
    id INT PRIMARY KEY AUTO_INCREMENT,
    orderIndex INT DEFAULT 0,
    name VARCHAR(255),
    refUrl VARCHAR(255),
    logo VARCHAR(255),
    thumbnail VARCHAR(255),
    backgroundImage VARCHAR(255),
    url VARCHAR(255),
    donateLink VARCHAR(255),
    gtm VARCHAR(255),
    analytics LONGTEXT DEFAULT NULL,
    advertisements VARCHAR(512) DEFAULT "[]",
    isDefault BOOLEAN,
    isActive BOOLEAN DEFAULT TRUE,
    metaPreset VARCHAR(1000) DEFAULT NULL
);

INSERT INTO `stations`(
    `id`,
    `orderIndex`,
    `name`,
    `refUrl`,
    `logo`,
    `thumbnail`,
    `backgroundImage`,
    `url`,
    `donateLink`,
    `gtm`,
    `analytics`,
    `advertisements`,
    `isDefault`,
    `isActive`,
    `metaPreset`
)
VALUES(
    1,
    1,
    'Eternity Ready Radio',
    '',
    '/stations/EternityReadyRadio_logo.png',
    '/stations/thumbnail/eternityRadio.png',
    '/stations/backgroundImage/EternityReadyRadio_background.png',
    'https://radio.eternityready.com:6448/stream',
    '',
    NULL,
    NULL,
    '[]',
    0,
    0,
    NULL
),(
    2,
    2,
    'VertiZontal Media',
    'vertizontal-media',
    '/stations/vertizontal.png',
    '/stations/thumbnail/vertizontal.png',
    '/stations/backgroundImage/vertizontal.png',
    'https://radio.vertizontalradio.com/listen/vr_-_vh/radio.mp3',
    '',
    NULL,
    NULL,
    '[]',
    0,
    1,
    NULL
),(
    3,
    3,
    'Fine Tune Radio',
    'fine-tune-radio',
    '/stations/fineTuneRadio.png',
    '/stations/thumbnail/fineTuneRadio.png',
    '/stations/backgroundImage/fineTuneRadio.png',
    'https://radio.finetuneradio.com/listen/fine_tune_radio/radio.mp3',
    '',
    NULL,
    NULL,
    '[]',
    0,
    1,
    NULL
),(
    4,
    4,
    'The Worship Channel',
    'the-worship-channel',
    '/stations/theWorshipChannel.png',
    '/stations/thumbnail/theWorshipChannel.png',
    '/stations/backgroundImage/theWorshipChannel.png',
    'https://das-edge10-live365-dal03.cdnstream.com/a45950',
    '',
    NULL,
    NULL,
    '[]',
    0,
    1,
    NULL
),(
    5,
    5,
    'KJOL',
    'kjol',
    '/stations/KJOL_logo.png',
    '/stations/thumbnail/KJOL_thumbnail.png',
    '/stations/backgroundImage/KJOL_background.png',
    'https://14993.live.streamtheworld.com/KJOLFMAAC.aac',
    '',
    NULL,
    NULL,
    '[]',
    0,
    1,
    NULL
),(
    6,
    6,
    'Affirm Southern Gospel Radio',
    'affirm-southern-gospel-radio',
    '/stations/AffirmSouthernGospelRadio_logo.png',
    '/stations/thumbnail/AffirmSouthernGospelRadio_thumbnail.png',
    '/stations/backgroundImage/AffirmSouthernGospelRadio_background.png',
    'https://das-edge12-live365-dal02.cdnstream.com/a38333',
    '',
    NULL,
    NULL,
    '[]',
    0,
    0,
    NULL
),(
    7,
    7,
    'Heaven\'s Country',
    'heavens-country',
    '/stations/Heaven\'sCountry_logo.png',
    '/stations/thumbnail/Heaven\'sCountry_thumbnail.png',
    '/stations/backgroundImage/Heaven\'sCountry_background.png',
    'https://das-edge11-live365-dal03.cdnstream.com/a66385',
    '',
    NULL,
    NULL,
    '[]',
    0,
    1,
    NULL
),(
    8,
    8,
    ' WBLB Family 1340',
    'wblb-family-1340',
    '/stations/WBLBFamily1340_logo.png',
    '/stations/thumbnail/WBLBFamily1340_thumbnail.png',
    '/stations/backgroundImage/WBLBFamily1340_background.png',
    'https://das-edge10-live365-dal03.cdnstream.com/a88004',
    'https://facebook.com',
    NULL,
    NULL,
    '[]',
    0,
    1,
    NULL
);